name: webscraping
on:
  workflow_dispatch:

jobs:
  webscraping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Create local changes
        run: |
            pip install --upgrade pip
            pip install get-chrome-driver --upgrade
            pip install -r requirements.txt
            cp file.html file_bak.html
            python main.py > file.html
            cat file_bak.html >> file.html
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}